### Get info
GET http://localhost:3000/info

### Get persons
GET http://localhost:3000/api/persons

### Get single person
GET http://localhost:3000/api/persons/669fbd5f00540f8b0cc51436

### Get single nonexisting person
GET http://localhost:3000/api/persons/1

### Delete person
DELETE http://localhost:3000/api/persons/669fafeb67e28cb07c3d8464

### Create person
POST http://localhost:3000/api/persons
Content-Type: application/json

{
  "name": "Marek Zelinka",
  "number": "040-123576"
}

### Update person
PUT http://localhost:3000/api/persons/669fbd5f00540f8b0cc51436
Content-Type: application/json

{
  "name": "Marek Zelinka",
  "number": "040-784512"
}