POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Marek Zelinka",
  "number": "040-2456768"
}

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/60a12fa505a5090bc4a8acfd

###
DELETE http://localhost:3001/api/persons/60a0eb8ae22dbb1878cf5d57