POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Marek Hellsman",
  "number": "040-241235"
}

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/60a141a6b72ada146c326860

###
PUT http://localhost:3001/api/persons/60a141a6b72ada146c326860
Content-Type: application/json

{
  "name": "Marek Zelinka",
  "number": "041-123456"
}

###
DELETE http://localhost:3001/api/persons/60a159b0b6ab212cc8d311d3