POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Marek Zelinka",
  "number": "040-2456768"
}

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/60a141a6b72ada146c326861

###
DELETE http://localhost:3001/api/persons/60a130774b03173a58a2d78d